<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Facades\DB;
use App\Services\BarcodeService;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $barcodeService = app(BarcodeService::class);

        $products = [
            // ==================== WALTON BRAND ====================
            [
                'name' => 'Walton 1 Gang 1 Way Switch',
                'sku' => 'TW1G1S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 193,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 1 gang 1 way switch for basic lighting control.',
                'long_description' => 'The Walton 1 Gang 1 Way Switch is a high-quality electrical switch designed for basic lighting control in residential and commercial spaces. Made with premium flame-retardant materials, it ensures safety and durability. The sleek white finish complements any interior decor. Easy to install with standard mounting boxes. Suitable for controlling a single light point from one location. Comes with silver alloy contacts for reliable performance and long service life.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.12,
            ],
            [
                'name' => 'Walton 1 Gang 2 Way Switch',
                'sku' => 'TW1G2S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 310,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 1 gang 2 way switch for multi-location lighting control.',
                'long_description' => 'The Walton 1 Gang 2 Way Switch allows you to control a single light point from two different locations, making it perfect for staircases, hallways, and large rooms. This switch features robust construction with high-grade thermoset material for excellent heat resistance. The mechanism ensures smooth operation with audible click feedback. Ideal for modern homes and offices where convenience and accessibility are priorities.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.13,
            ],
            [
                'name' => 'Walton 2 Gang 1 Way Switch',
                'sku' => 'TW2G1S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 380,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 2 gang 1 way switch for independent control of two circuits.',
                'long_description' => 'The Walton 2 Gang 1 Way Switch provides independent control for two separate lighting circuits from a single location. This space-saving design is perfect for rooms with multiple light fixtures. Each gang operates independently, allowing flexible lighting arrangements. Constructed with high-quality polycarbonate material that resists impact and discoloration. Features silver-nickel contact points for excellent conductivity and minimal sparking.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.18,
            ],
            [
                'name' => 'Walton 2 Gang 2 Way Switch',
                'sku' => 'TW2G2S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 380,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 2 gang 2 way switch for dual circuit control from multiple locations.',
                'long_description' => 'The Walton 2 Gang 2 Way Switch offers advanced lighting control with two circuits that can each be controlled from two different locations. This versatile switch is ideal for large living spaces, corridors, and commercial areas. The modular design allows for easy installation and maintenance. Engineered with precision mechanisms for consistent performance. The white finish is UV-resistant and maintains its appearance over time.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.19,
            ],
            [
                'name' => 'Walton 3 Gang 1 Way Switch',
                'sku' => 'TW3G1S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 500,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 3 gang 1 way switch for controlling three separate lighting circuits.',
                'long_description' => 'The Walton 3 Gang 1 Way Switch is designed for efficient control of three separate lighting circuits from a single point. Perfect for open-plan spaces, offices, and retail environments. Each switch module is independently operable with smooth toggle action. The robust housing provides superior insulation and protection. Complies with international safety standards and comes with a 2-year warranty against manufacturing defects.',
                'length' => 15.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.24,
            ],
            [
                'name' => 'Walton 4 Gang 1 Way Switch',
                'sku' => 'TW4G1S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 525,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 4 gang 1 way switch for centralized control of four lighting circuits.',
                'long_description' => 'The Walton 4 Gang 1 Way Switch provides centralized control for four separate lighting circuits, making it an excellent choice for large residential and commercial installations. The compact design saves wall space while offering maximum functionality. Manufactured with premium-grade materials that ensure electrical safety and mechanical durability. Features clearly marked terminals for easy wiring. Ideal for conference rooms, classrooms, and entertainment areas.',
                'length' => 19.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.30,
            ],
            [
                'name' => 'Walton 2 Gang Power Switch',
                'sku' => 'TW2PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 495,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 2 gang power switch for appliance control.',
                'long_description' => 'The Walton 2 Gang Power Switch is specially designed for controlling electrical appliances with higher power requirements. Each gang can handle up to 13A of current, making it suitable for fans, air conditioners, heaters, and other medium-power appliances. Features sturdy construction with brass terminals for secure connections. The rocker switch mechanism ensures comfortable operation with a satisfying tactile feel. Comes with safety shutters for added protection.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.20,
            ],
            [
                'name' => 'Walton 3 Gang 13A Power Switch',
                'sku' => 'TW3PS13A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 540,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 3 gang 13A power switch for heavy-duty appliances.',
                'long_description' => 'The Walton 3 Gang 13A Power Switch is built for heavy-duty appliance control with each gang rated at 13A capacity. This switch is perfect for controlling multiple high-power appliances like air conditioners, water heaters, and kitchen equipment. The switch features silver alloy contacts that minimize wear and ensure reliable operation over thousands of cycles. The surface is scratch-resistant and easy to clean. Backed by rigorous quality testing for safety and performance.',
                'length' => 15.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.26,
            ],
            [
                'name' => 'Walton 5 Gang Power Switch',
                'sku' => 'TW5PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 630,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 5 gang power switch for multi-appliance control.',
                'long_description' => 'The Walton 5 Gang Power Switch offers comprehensive control for up to five appliances from a single wall location. Each gang is independently rated and provides reliable on/off control. This versatile switch is ideal for home theaters, server rooms, workshop areas, and commercial kitchens. The modular grid design allows for easy customization and expansion. Constructed with fire-retardant ABS plastic that meets UL94 V-0 rating for maximum safety.',
                'length' => 22.0,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.35,
            ],
            [
                'name' => 'Walton Double Pole Switch',
                'sku' => 'TWDBS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 370,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand double pole switch for complete circuit isolation.',
                'long_description' => 'The Walton Double Pole Switch provides complete circuit isolation by simultaneously disconnecting both live and neutral conductors. This safety-critical switch is essential for appliances that require full disconnection for maintenance or safety reasons. Ideal for water heaters, AC units, and industrial equipment. Features positive break action with clear ON/OFF indication. The heavy-duty construction ensures long-term reliability and compliance with international electrical safety standards.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.8,
                'weight' => 0.22,
            ],
            [
                'name' => 'Walton 3 Gang Push Button Switch',
                'sku' => 'TW3PRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 670,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 3 gang push button switch for momentary contact applications.',
                'long_description' => 'The Walton 3 Gang Push Button Switch features momentary contact operation, ideal for doorbells, alarms, intercoms, and industrial control applications. Each push button is spring-returned to its normal position, providing temporary circuit closure only while pressed. The switch is designed for high-frequency operation with durable mechanical components. The sleek, modern appearance adds a professional touch to any installation. Suitable for both residential and commercial use.',
                'length' => 15.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.25,
            ],
            [
                'name' => 'Walton TV/Antenna Switch',
                'sku' => 'TWTVS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 550,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand TV/antenna switch for signal routing.',
                'long_description' => 'The Walton TV/Antenna Switch is designed for routing television and antenna signals between multiple sources or destinations. This switch features high-quality coaxial connectors that maintain signal integrity with minimal attenuation. Perfect for homes with multiple TV points, satellite dishes, or cable connections. The switch mechanism ensures positive contact and reliable signal transmission. The compact wall-mount design blends seamlessly with standard electrical switch plates.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.15,
            ],
            [
                'name' => 'Walton Telephone Line Switch',
                'sku' => 'TWTS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 550,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand telephone/communication line switch.',
                'long_description' => 'The Walton Telephone Line Switch enables convenient switching of telephone or communication lines between different devices. This switch is compatible with standard RJ11 and RJ12 connectors and supports both analog and digital signals. Ideal for offices, call centers, and home communication setups. The switch features high-quality gold-plated contacts that ensure low resistance and reliable signal quality. Easy to install in standard electrical back boxes.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.15,
            ],
            [
                'name' => 'Walton 20A Double Pole Safety Switch',
                'sku' => 'TWDPSS20A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 910,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 20A double pole switch for high-current appliances like water heaters.',
                'long_description' => 'The Walton 20A Double Pole Safety Switch is designed for high-current appliances such as water heaters, cooktops, and heavy-duty pumps. This switch disconnects both live and neutral lines simultaneously, providing complete electrical isolation for safety during maintenance. The 20A rating ensures reliable performance with demanding loads. Features a robust mechanism with silver alloy contacts for excellent conductivity. Comes with a red ON indicator for clear status visibility.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 4.0,
                'weight' => 0.32,
            ],
            [
                'name' => 'Walton 45A Double Pole Safety Switch',
                'sku' => 'TWDPSS45A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1145,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand 45A double pole switch for heavy-duty appliances like AC units.',
                'long_description' => 'The Walton 45A Double Pole Safety Switch is a heavy-duty switching solution for very high-current appliances including large air conditioning units, industrial machinery, and electric furnaces. The switch is engineered for 45A continuous load capacity with a high breaking capacity for safety. Both live and neutral conductors are disconnected with positive break action. The housing is constructed from high-grade engineering plastic with excellent thermal and electrical insulation properties.',
                'length' => 15.5,
                'width' => 10.0,
                'height' => 4.5,
                'weight' => 0.55,
            ],
            [
                'name' => 'Walton Fan Speed Regulator',
                'sku' => 'TWFR',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 995,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand fan speed regulator for smooth ceiling fan control.',
                'long_description' => 'The Walton Fan Speed Regulator provides smooth and precise speed control for ceiling fans in residential and commercial spaces. This regulator utilizes advanced electronic control technology to deliver consistent performance with minimal power loss. The rotary knob design offers intuitive speed selection with multiple speed levels. The compact body fits standard switch boxes, making it an ideal upgrade for modern interiors. Built with surge protection for longevity.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 4.0,
                'weight' => 0.20,
            ],
            [
                'name' => 'Walton Fan Regulator with Switch',
                'sku' => 'TWFRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1045,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand fan regulator with integrated on/off switch.',
                'long_description' => 'The Walton Fan Regulator with Integrated Switch combines fan speed control and power switching in a single unit. This all-in-one solution eliminates the need for a separate wall switch, reducing installation complexity and saving wall space. The regulator features a smooth rotary dial with a positive OFF position and multiple speed settings. The elegant design complements modern interiors while the electronic circuitry ensures energy-efficient fan operation.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 4.0,
                'weight' => 0.24,
            ],
            [
                'name' => 'Walton Dimmer Switch',
                'sku' => 'TWDS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 600,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand dimmer switch for adjustable lighting levels.',
                'long_description' => 'The Walton Dimmer Switch offers adjustable lighting control for creating the perfect ambiance in any room. This switch supports incandescent and dimmable LED loads, providing smooth dimming from full brightness to minimal glow. The intuitive rotary dial allows precise brightness selection. Advanced components ensure flicker-free dimming and compatibility with most modern bulbs. The switch also features soft-start technology to extend bulb life and reduce inrush current.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.8,
                'weight' => 0.18,
            ],
            [
                'name' => 'Walton Bell Push Button',
                'sku' => 'TWBP',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 143,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Walton brand bell push button for doorbell applications.',
                'long_description' => 'The Walton Bell Push Button is designed for doorbell and calling systems in residential and commercial buildings. This durable push button features a large, easy-to-press surface with a spring-return mechanism for reliable operation. The high-quality contacts ensure consistent electrical connection every time. The sleek design and durable finish resist corrosion and maintain appearance over years of use. Easy to install with standard wiring connections.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.0,
                'weight' => 0.08,
            ],

            // ==================== FIONA BRAND ====================
            [
                'name' => 'Fiona 1 Gang 1 Way Switch',
                'sku' => 'F1GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 193,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 1 gang 1 way switch for basic lighting control.',
                'long_description' => 'The Fiona 1 Gang 1 Way Switch offers reliable and stylish lighting control for homes and offices. This switch features a contemporary design with a smooth, white finish that complements modern interiors. Built with high-quality materials and precision engineering, it ensures smooth operation and long service life. The 1-way configuration is perfect for controlling a single light point from one location, making it suitable for bedrooms, living rooms, and corridors.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.12,
            ],
            [
                'name' => 'Fiona 1 Gang 2 Way Switch',
                'sku' => 'F1GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 310,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 1 gang 2 way switch for multi-location lighting control.',
                'long_description' => 'The Fiona 1 Gang 2 Way Switch enables convenient control of a single light from two different positions. This feature is essential for staircases, large rooms, and hallways where access to lighting control from multiple points is desired. The switch employs robust internal mechanisms with silver contacts for reliable performance. Its elegant design features a smooth rocker action that provides positive tactile feedback with every operation.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.13,
            ],
            [
                'name' => 'Fiona 2 Gang 1 Way Switch',
                'sku' => 'F2GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 370,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 2 gang 1 way switch for independent control of two circuits.',
                'long_description' => 'The Fiona 2 Gang 1 Way Switch provides independent control for two lighting circuits in a single, space-efficient unit. This switch is ideal for rooms with two separate light fixtures or for controlling a light and an exhaust fan from the same location. The modular design features individual rocker switches with clear separation for intuitive operation. Manufactured to high standards with flame-retardant materials for enhanced safety.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.18,
            ],
            [
                'name' => 'Fiona 2 Gang 2 Way Switch',
                'sku' => 'F2GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 450,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 2 gang 2 way switch for dual circuit control from multiple locations.',
                'long_description' => 'The Fiona 2 Gang 2 Way Switch offers sophisticated lighting control for two separate circuits, each controllable from two different locations. This versatile solution is perfect for open-plan living spaces, corridors, and large offices. The switch features high-quality components with silver alloy contacts for excellent conductivity and minimal arcing. The contemporary design with smooth-touch finish adds aesthetic value to any installation.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.19,
            ],
            [
                'name' => 'Fiona 3 Gang 1 Way Switch',
                'sku' => 'F3GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 470,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 3 gang 1 way switch for controlling three separate lighting circuits.',
                'long_description' => 'The Fiona 3 Gang 1 Way Switch provides centralized control of three lighting circuits from a single point. This switch is an excellent choice for living rooms, entertainment areas, and offices where multiple light sources need convenient control. Each gang operates independently with a smooth rocker mechanism. The switch is constructed from high-quality materials with excellent insulation properties, ensuring electrical safety and durability.',
                'length' => 15.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.24,
            ],
            [
                'name' => 'Fiona 4 Gang 1 Way Switch',
                'sku' => 'F4GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 565,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 4 gang 1 way switch for centralized control of four lighting circuits.',
                'long_description' => 'The Fiona 4 Gang 1 Way Switch offers comprehensive lighting control for up to four separate circuits, all from a single wall location. Perfect for larger spaces, conference rooms, retail environments, and modern homes. The switch features a sleek design with well-spaced rockers for easy operation. The high-quality construction includes silver-nickel contacts for consistent performance and long-term reliability.',
                'length' => 19.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.30,
            ],
            [
                'name' => 'Fiona 2 Gang Power Switch',
                'sku' => 'F2PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 470,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 2 gang power switch for appliance control.',
                'long_description' => 'The Fiona 2 Gang Power Switch is designed for reliable control of electrical appliances and equipment. Each gang is rated for standard appliance loads and features robust contacts for consistent performance. This switch is ideal for controlling fans, televisions, pumps, and other household appliances. The modern design with premium white finish fits seamlessly with contemporary decor. Easy to install with clear wiring markings.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.20,
            ],
            [
                'name' => 'Fiona 3 Gang 13A Power Switch',
                'sku' => 'F3PS13A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 560,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 3 gang 13A power switch for heavy-duty appliances.',
                'long_description' => 'The Fiona 3 Gang 13A Power Switch is engineered for heavy-duty appliance control with each gang capable of handling 13A loads. This robust switch is perfect for air conditioning units, water heaters, kitchen appliances, and workshop equipment. Features high-quality brass terminals with corrosion resistance and excellent conductivity. The rocker switches have a satisfying operation with audible click confirmation.',
                'length' => 15.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.26,
            ],
            [
                'name' => 'Fiona 5 Gang Power Switch',
                'sku' => 'F5PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 715,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 5 gang power switch for multi-appliance control.',
                'long_description' => 'The Fiona 5 Gang Power Switch provides extensive control for multiple appliances in a single unit. This switch is ideal for home theaters, server rooms, professional workshops, and commercial kitchens. Each gang offers independent control with clear visual indication of status. The switch is constructed with premium materials that offer excellent heat resistance and electrical insulation. Features easy wiring with clearly marked terminals.',
                'length' => 22.0,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.35,
            ],
            [
                'name' => 'Fiona Double Pole Switch',
                'sku' => 'FDBS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 485,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand double pole switch for complete circuit isolation.',
                'long_description' => 'The Fiona Double Pole Switch offers complete electrical isolation by disconnecting both live and neutral conductors. This safety switch is essential for appliances requiring full disconnection, including water heaters, AC units, and industrial machinery. The switch features positive break action with clear ON/OFF indication. Built to high safety standards with reinforced insulation and durable mechanical components.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.8,
                'weight' => 0.22,
            ],
            [
                'name' => 'Fiona 3 Gang Push Button Switch',
                'sku' => 'F3PRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 635,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 3 gang push button switch for momentary contact applications.',
                'long_description' => 'The Fiona 3 Gang Push Button Switch is designed for momentary contact applications such as doorbells, alarms, signaling systems, and industrial controls. Each push button is spring-returned to provide temporary circuit closure only when pressed. The switch features durable mechanical components tested for high-frequency operation. The attractive design makes it suitable for both residential and commercial installations.',
                'length' => 15.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.25,
            ],
            [
                'name' => 'Fiona TV/Antenna Switch',
                'sku' => 'FTVS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand TV/antenna switch for signal routing.',
                'long_description' => 'The Fiona TV/Antenna Switch enables efficient routing of television and antenna signals between multiple sources. This switch features high-quality connectors that ensure minimal signal loss and excellent impedance matching. Ideal for homes with multiple TV points, satellite systems, or cable services. The switch mechanism provides positive connection with consistent signal integrity. The wall-mount design integrates seamlessly with standard switch plates.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.15,
            ],
            [
                'name' => 'Fiona Telephone Line Switch',
                'sku' => 'FTS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand telephone/communication line switch.',
                'long_description' => 'The Fiona Telephone Line Switch facilitates convenient switching of telephone and communication lines between multiple devices. This switch is compatible with standard telephone connectors and supports both analog and digital signals. Perfect for offices, call centers, and home communication systems. The high-quality contacts ensure reliable signal transmission with minimal attenuation. Easy to install in standard electrical boxes.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.15,
            ],
            [
                'name' => 'Fiona 20A Double Pole Safety Switch',
                'sku' => 'FDPS20A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 850,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 20A double pole switch for high-current appliances.',
                'long_description' => 'The Fiona 20A Double Pole Safety Switch provides reliable disconnection for high-current appliances including water heaters, cooktops, and pool pumps. This switch simultaneously disconnects both live and neutral for complete safety. The 20A rating ensures compatibility with demanding electrical loads. Features a sturdy construction with silver alloy contacts for excellent conductivity. The clear ON/OFF indicator provides visual status confirmation.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 4.0,
                'weight' => 0.32,
            ],
            [
                'name' => 'Fiona 45A Double Pole Safety Switch',
                'sku' => 'FDPS45A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1030,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 45A double pole switch for heavy-duty appliances.',
                'long_description' => 'The Fiona 45A Double Pole Safety Switch is engineered for extreme high-current applications including large air conditioning units, industrial equipment, and electric heating systems. This switch can handle continuous 45A loads with a high breaking capacity for safety. Both poles are disconnected simultaneously with positive break action. The robust housing provides excellent thermal and electrical insulation. Suitable for demanding commercial and industrial environments.',
                'length' => 15.5,
                'width' => 10.0,
                'height' => 4.5,
                'weight' => 0.55,
            ],
            [
                'name' => 'Fiona Fan Speed Regulator',
                'sku' => 'FFR',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 915,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand fan speed regulator for smooth fan control.',
                'long_description' => 'The Fiona Fan Speed Regulator offers smooth and reliable speed control for ceiling fans in homes and offices. Using advanced electronic technology, this regulator provides consistent performance with multiple speed settings. The rotary knob design allows intuitive speed selection from low to high. The compact and elegant design fits seamlessly with modern interiors. Built with protection against voltage fluctuations for enhanced longevity.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 4.0,
                'weight' => 0.20,
            ],
            [
                'name' => 'Fiona Fan Regulator with Switch',
                'sku' => 'FFRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 915,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand fan regulator with integrated on/off switch.',
                'long_description' => 'The Fiona Fan Regulator with Integrated Switch provides both on/off control and speed regulation in a single convenient unit. This all-in-one solution saves wall space and simplifies installation. The regulator features a smooth rotary knob with a positive OFF position and stepless speed control. The electronic design ensures energy-efficient operation and minimal power loss. The modern appearance complements any interior design style.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 4.0,
                'weight' => 0.24,
            ],
            [
                'name' => 'Fiona Dimmer Switch',
                'sku' => 'FDS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 625,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand dimmer switch for adjustable lighting levels.',
                'long_description' => 'The Fiona Dimmer Switch provides smooth adjustable lighting control for creating perfect ambiance in any space. Compatible with both incandescent and dimmable LED bulbs, this switch offers flicker-free dimming from maximum to minimum brightness. The large rotary dial provides precise control with a smooth action. Features soft-start technology that extends bulb life by reducing inrush current. The elegant design adds sophistication to any room.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.8,
                'weight' => 0.18,
            ],
            [
                'name' => 'Fiona Bell Push Button',
                'sku' => 'FBP',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 188,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand bell push button for doorbell applications.',
                'long_description' => 'The Fiona Bell Push Button is a reliable and stylish solution for doorbell and calling systems. Designed for both residential and commercial applications, this push button features a large, easy-to-press surface with a responsive spring-return mechanism. The high-quality contacts ensure consistent electrical connection with every press. The durable finish resists wear and maintains its appearance over time.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.0,
                'weight' => 0.08,
            ],
            [
                'name' => 'Fiona 5 Gang Power Switch with USB Ports',
                'sku' => 'F5PS-USB',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1125,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Fiona brand 5 gang power switch with integrated USB charging ports.',
                'long_description' => 'The Fiona 5 Gang Power Switch with Integrated USB Ports offers the ultimate convenience for modern homes and offices. This innovative switch combines five independently controlled power outlets with dual USB charging ports for smartphones, tablets, and other devices. The USB ports provide fast charging with smart current detection. The switch is designed with premium materials and features an elegant white finish. Perfect for entertainment areas, workspaces, and hospitality environments.',
                'length' => 22.0,
                'width' => 8.5,
                'height' => 3.8,
                'weight' => 0.42,
            ],

            // ==================== PENTA BRAND ====================
            [
                'name' => 'Penta 1 Gang 1 Way Switch',
                'sku' => 'P1GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 203,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 1 gang 1 way switch for basic lighting control.',
                'long_description' => 'The Penta 1 Gang 1 Way Switch delivers reliable basic lighting control with a touch of modern style. This switch features a clean, minimalist design with a smooth white finish that enhances any interior. Built with high-quality materials and precision mechanisms for smooth operation and long service life. Ideal for bedrooms, living rooms, and hallways where simple single-point lighting control is required.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.12,
            ],
            [
                'name' => 'Penta 1 Gang 2 Way Switch',
                'sku' => 'P1GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 320,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 1 gang 2 way switch for multi-location lighting control.',
                'long_description' => 'The Penta 1 Gang 2 Way Switch enables convenient control of a single light source from two different locations. This is ideal for staircases, long hallways, and large rooms where access to lighting control from multiple points is essential. The switch features reliable internal mechanisms with high-quality contacts for consistent performance. The modern design includes a comfortable rocker action with positive tactile feedback.',
                'length' => 8.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.13,
            ],
            [
                'name' => 'Penta 2 Gang 1 Way Switch',
                'sku' => 'P2GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 385,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 2 gang 1 way switch for independent control of two circuits.',
                'long_description' => 'The Penta 2 Gang 1 Way Switch offers independent control for two separate lighting circuits in a single, space-efficient unit. This versatile switch is perfect for rooms with multiple light fixtures or for controlling a light and an exhaust fan from the same location. The switch features individual rockers with clear separation for intuitive operation. Constructed from flame-retardant materials for enhanced safety.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.18,
            ],
            [
                'name' => 'Penta 2 Gang 2 Way Switch',
                'sku' => 'P2GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 470,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 2 gang 2 way switch for dual circuit control from multiple locations.',
                'long_description' => 'The Penta 2 Gang 2 Way Switch provides sophisticated lighting control for two separate circuits, each controllable from two different positions. This advanced solution is ideal for open-plan areas, corridors, and large office spaces. The switch is built with high-quality components including silver alloy contacts for excellent conductivity. The contemporary design and smooth-touch finish add a premium feel to any installation.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.19,
            ],
            [
                'name' => 'Penta 3 Gang 1 Way Switch',
                'sku' => 'P3GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 480,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 3 gang 1 way switch for controlling three separate lighting circuits.',
                'long_description' => 'The Penta 3 Gang 1 Way Switch offers centralized control for three lighting circuits from a single location. Perfect for living rooms, entertainment areas, offices, and retail environments. Each gang operates independently with smooth rocker mechanisms. The switch is manufactured from high-grade materials with excellent insulating properties, ensuring electrical safety and long-term durability.',
                'length' => 15.5,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.24,
            ],
            [
                'name' => 'Penta 4 Gang 1 Way Switch',
                'sku' => 'P4GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 4 gang 1 way switch for centralized control of four lighting circuits.',
                'long_description' => 'The Penta 4 Gang 1 Way Switch provides comprehensive lighting control for up to four circuits from a single wall location. This is ideal for larger spaces including conference rooms, classrooms, retail stores, and modern homes. The switch features a clean design with well-spaced rockers for comfortable operation. Premium construction includes silver-nickel contacts for consistent performance and reliability.',
                'length' => 19.0,
                'width' => 8.5,
                'height' => 3.2,
                'weight' => 0.30,
            ],
            [
                'name' => 'Penta 2 Gang Power Switch',
                'sku' => 'P2PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 480,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 2 gang power switch for appliance control.',
                'long_description' => 'The Penta 2 Gang Power Switch is designed for reliable control of electrical appliances in homes and offices. Each gang is rated for standard appliance loads and features robust contacts for consistent performance. This switch is ideal for controlling fans, televisions, pumps, and other household appliances. The modern design with a premium white finish complements any interior. Easy to install with clearly marked terminals.',
                'length' => 12.0,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.20,
            ],
            [
                'name' => 'Penta 3 Gang 13A Power Switch',
                'sku' => 'P3PS13A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 3 gang 13A power switch for heavy-duty appliances.',
                'long_description' => 'The Penta 3 Gang 13A Power Switch is engineered for heavy-duty appliance control, with each gang capable of handling 13A loads. This robust switch is suitable for air conditioning units, water heaters, kitchen appliances, and workshop equipment. Features high-quality brass terminals with corrosion resistance and excellent conductivity. The rocker switches provide satisfying operation with audible click feedback.',
                'length' => 15.5,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.26,
            ],
            [
                'name' => 'Penta 8 Gang Power Switch',
                'sku' => 'P8PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 730,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'short_description' => 'Penta brand 8 gang power switch for extensive multi-appliance control.',
                'long_description' => 'The Penta 8 Gang Power Switch offers extensive control for multiple appliances in a single, convenient unit. This switch is ideal for professional workstations, home theaters, server rooms, commercial kitchens, and workshop environments. Each gang operates independently with clear visual indication of on/off status. The switch is constructed with premium materials offering excellent heat resistance and insulation. Features easy wiring with clearly marked terminals and includes mounting screws for secure installation. The wide 8-gang design provides comprehensive control while saving valuable wall space.',
                'length' => 30.0,
                'width' => 8.5,
                'height' => 3.5,
                'weight' => 0.48,
            ],
        ];

        foreach ($products as $product) {

            /*
            |--------------------------------------------------------------------------
            | Generate barcode only when creating a new product
            |--------------------------------------------------------------------------
            |
            | Existing product-এর barcode overwrite হবে না।
            |
            */

            $existingProduct = Product::where('sku', $product['sku'])->first();

            if (!$existingProduct) {
                $product['barcode'] = $barcodeService->generateUniqueBarcode();
            } elseif (empty($existingProduct->barcode)) {
                /*
                |--------------------------------------------------------------------------
                | Existing product আছে কিন্তু barcode নেই
                |--------------------------------------------------------------------------
                */
                $existingProduct->update([
                    'barcode' => $barcodeService->generateUniqueBarcode(
                        null,
                        $existingProduct->id
                    ),
                ]);
            }

            Product::updateOrCreate(
                ['sku' => $product['sku']],
                $product
            );
        }
    }
}