<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Product;
use Illuminate\Support\Facades\DB;

class ProductSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {

        $products = [
            [
                'name' => 'TW1G1S',
                'sku' => 'TW1G1S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 193,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 1 gang 1 way switch for basic lighting control.',
            ],
            [
                'name' => 'TW1G2S',
                'sku' => 'TW1G2S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 310,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 1 gang 2 way switch for multi-location lighting control.',
            ],
            [
                'name' => 'TW2G1S',
                'sku' => 'TW2G1S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 380,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 2 gang 1 way switch for independent control of two circuits.',
            ],
            [
                'name' => 'TW2G2S',
                'sku' => 'TW2G2S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 380,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 2 gang 2 way switch for dual circuit control from multiple locations.',
            ],
            [
                'name' => 'TW3G1S',
                'sku' => 'TW3G1S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 500,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 3 gang 1 way switch for controlling three separate lighting circuits.',
            ],
            [
                'name' => 'TW4G1S',
                'sku' => 'TW4G1S',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 525,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 4 gang 1 way switch for centralized control of four lighting circuits.',
            ],
            [
                'name' => 'TW2PS',
                'sku' => 'TW2PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 495,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 2 gang power switch for appliance control.',
            ],
            [
                'name' => 'TW3PS13A',
                'sku' => 'TW3PS13A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 540,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 3 gang 13A power switch for heavy-duty appliances.',
            ],
            [
                'name' => 'TW5PS',
                'sku' => 'TW5PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 630,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 5 gang power switch for multi-appliance control.',
            ],
            [
                'name' => 'TWDBS',
                'sku' => 'TWDBS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 370,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand double pole switch for complete circuit isolation.',
            ],
            [
                'name' => 'TW3PRS',
                'sku' => 'TW3PRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 670,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 3 gang push button switch for momentary contact applications.',
            ],
            [
                'name' => 'TWTVS',
                'sku' => 'TWTVS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 550,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand TV/antenna switch for signal routing.',
            ],
            [
                'name' => 'TWTS',
                'sku' => 'TWTS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 550,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand telephone/communication line switch.',
            ],
            [
                'name' => 'TWDPSS20A',
                'sku' => 'TWDPSS20A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 910,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 20A double pole switch for high-current appliances like water heaters.',
            ],
            [
                'name' => 'TWDPSS45A',
                'sku' => 'TWDPSS45A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1145,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand 45A double pole switch for heavy-duty appliances like AC units.',
            ],
            [
                'name' => 'TWFR',
                'sku' => 'TWFR',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 995,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand fan speed regulator for smooth ceiling fan control.',
            ],
            [
                'name' => 'TWFRS',
                'sku' => 'TWFRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1045,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand fan regulator with integrated on/off switch.',
            ],
            [
                'name' => 'TWDS',
                'sku' => 'TWDS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 600,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand dimmer switch for adjustable lighting levels.',
            ],
            [
                'name' => 'TWBP',
                'sku' => 'TWBP',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 143,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Walton brand bell push button for doorbell applications.',
            ],
            [
                'name' => 'F1GS1',
                'sku' => 'F1GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 193,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 1 gang 1 way switch for basic lighting control.',
            ],
            [
                'name' => 'F1GS2',
                'sku' => 'F1GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 310,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 1 gang 2 way switch for multi-location lighting control.',
            ],
            [
                'name' => 'F2GS1',
                'sku' => 'F2GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 370,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 2 gang 1 way switch for independent control of two circuits.',
            ],
            [
                'name' => 'F2GS2',
                'sku' => 'F2GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 450,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 2 gang 2 way switch for dual circuit control from multiple locations.',
            ],
            [
                'name' => 'F3GS1',
                'sku' => 'F3GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 470,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 3 gang 1 way switch for controlling three separate lighting circuits.',
            ],
            [
                'name' => 'F4GS1',
                'sku' => 'F4GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 565,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 4 gang 1 way switch for centralized control of four lighting circuits.',
            ],
            [
                'name' => 'F2PS',
                'sku' => 'F2PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 470,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 2 gang power switch for appliance control.',
            ],
            [
                'name' => 'F3PS13A',
                'sku' => 'F3PS13A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 560,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 3 gang 13A power switch for heavy-duty appliances.',
            ],
            [
                'name' => 'F5PS',
                'sku' => 'F5PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 715,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 5 gang power switch for multi-appliance control.',
            ],
            [
                'name' => 'FDBS',
                'sku' => 'FDBS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 485,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand double pole switch for complete circuit isolation.',
            ],
            [
                'name' => 'F3PRS',
                'sku' => 'F3PRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 635,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 3 gang push button switch for momentary contact applications.',
            ],
            [
                'name' => 'FTVS',
                'sku' => 'FTVS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand TV/antenna switch for signal routing.',
            ],
            [
                'name' => 'FTS',
                'sku' => 'FTS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand telephone/communication line switch.',
            ],
            [
                'name' => 'FDPS20A',
                'sku' => 'FDPS20A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 850,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 20A double pole switch for high-current appliances.',
            ],
            [
                'name' => 'FDPS45A',
                'sku' => 'FDPS45A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1030,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 45A double pole switch for heavy-duty appliances.',
            ],
            [
                'name' => 'FFR',
                'sku' => 'FFR',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 915,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand fan speed regulator for smooth fan control.',
            ],
            [
                'name' => 'FFRS',
                'sku' => 'FFRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 915,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand fan regulator with integrated on/off switch.',
            ],
            [
                'name' => 'FDS',
                'sku' => 'FDS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 625,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand dimmer switch for adjustable lighting levels.',
            ],
            [
                'name' => 'FBP',
                'sku' => 'FBP',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 188,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand bell push button for doorbell applications.',
            ],
            [
                'name' => 'F5PS-USB',
                'sku' => 'F5PS-USB',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1125,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Fiona brand 5 gang power switch with integrated USB charging ports.',
            ],
            [
                'name' => 'P1GS1',
                'sku' => 'P1GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 203,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 1 gang 1 way switch for basic lighting control.',
            ],
            [
                'name' => 'P1GS2',
                'sku' => 'P1GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 320,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 1 gang 2 way switch for multi-location lighting control.',
            ],
            [
                'name' => 'P2GS1',
                'sku' => 'P2GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 385,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 2 gang 1 way switch for independent control of two circuits.',
            ],
            [
                'name' => 'P2GS2',
                'sku' => 'P2GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 470,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 2 gang 2 way switch for dual circuit control from multiple locations.',
            ],
            [
                'name' => 'P3GS1',
                'sku' => 'P3GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 480,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 3 gang 1 way switch for controlling three separate lighting circuits.',
            ],
            [
                'name' => 'P4GS1',
                'sku' => 'P4GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 4 gang 1 way switch for centralized control of four lighting circuits.',
            ],
            [
                'name' => 'P2PS',
                'sku' => 'P2PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 480,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 2 gang power switch for appliance control.',
            ],
            [
                'name' => 'P3PS13A',
                'sku' => 'P3PS13A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 3 gang 13A power switch for heavy-duty appliances.',
            ],
            [
                'name' => 'P8PS',
                'sku' => 'P8PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 730,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 8 gang power switch for extensive multi-appliance control.',
            ],
            [
                'name' => 'PDBS',
                'sku' => 'PDBS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 500,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand double pole switch for complete circuit isolation.',
            ],
            [
                'name' => 'P3PRS15A',
                'sku' => 'P3PRS15A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 670,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 3 gang 15A push button switch for momentary heavy-load control.',
            ],
            [
                'name' => 'PTVS',
                'sku' => 'PTVS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 585,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand TV/antenna switch for signal routing.',
            ],
            [
                'name' => 'PTS',
                'sku' => 'PTS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 585,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand telephone/communication line switch.',
            ],
            [
                'name' => 'PDPS20A',
                'sku' => 'PDPS20A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 860,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 20A double pole switch for high-current appliances.',
            ],
            [
                'name' => 'PDPS45A',
                'sku' => 'PDPS45A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1045,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand 45A double pole switch for heavy-duty appliances.',
            ],
            [
                'name' => 'PFR',
                'sku' => 'PFR',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 925,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand fan speed regulator for smooth fan control.',
            ],
            [
                'name' => 'PFRS',
                'sku' => 'PFRS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 940,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand fan regulator with integrated on/off switch.',
            ],
            [
                'name' => 'PDS',
                'sku' => 'PDS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 640,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand dimmer switch for adjustable lighting levels.',
            ],
            [
                'name' => 'PBP',
                'sku' => 'PBP',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 198,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Penta brand bell push button for doorbell applications.',
            ],
            [
                'name' => 'GW1GS1',
                'sku' => 'GW1GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 188,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 1 gang 1 way switch for basic lighting control.',
            ],
            [
                'name' => 'GW1GS2',
                'sku' => 'GW1GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 270,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 1 gang 2 way switch for multi-location lighting control.',
            ],
            [
                'name' => 'GW2GS1',
                'sku' => 'GW2GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 285,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 2 gang 1 way switch for independent control of two circuits.',
            ],
            [
                'name' => 'GW2GS2',
                'sku' => 'GW2GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 335,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 2 gang 2 way switch for dual circuit control from multiple locations.',
            ],
            [
                'name' => 'GW3GS1',
                'sku' => 'GW3GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 355,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 3 gang 1 way switch for controlling three separate lighting circuits.',
            ],
            [
                'name' => 'GW4GS1',
                'sku' => 'GW4GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 415,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 4 gang 1 way switch for centralized control of four lighting circuits.',
            ],
            [
                'name' => 'GW2PS',
                'sku' => 'GW2PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 695,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 2 gang power switch for appliance control.',
            ],
            [
                'name' => 'GW3PS13A',
                'sku' => 'GW3PS13A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 465,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 3 gang 13A power switch for heavy-duty appliances.',
            ],
            [
                'name' => 'GW8PS',
                'sku' => 'GW8PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 485,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 8 gang power switch for extensive multi-appliance control.',
            ],
            [
                'name' => 'GWDBS',
                'sku' => 'GWDBS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 215,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand double pole switch for complete circuit isolation.',
            ],
            [
                'name' => 'GW3PRS15A',
                'sku' => 'GW3PRS15A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 570,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 3 gang 15A push button switch for momentary heavy-load control.',
            ],
            [
                'name' => 'GWTVS',
                'sku' => 'GWTVS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 400,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand TV/antenna switch for signal routing.',
            ],
            [
                'name' => 'GWTS',
                'sku' => 'GWTS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 400,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand telephone/communication line switch.',
            ],
            [
                'name' => 'GWDPS20A',
                'sku' => 'GWDPS20A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 700,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 20A double pole switch for high-current appliances.',
            ],
            [
                'name' => 'GWDPS45A',
                'sku' => 'GWDPS45A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 950,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand 45A double pole switch for heavy-duty appliances.',
            ],
            [
                'name' => 'GWFR',
                'sku' => 'GWFR',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 735,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand fan speed regulator for smooth fan control.',
            ],
            [
                'name' => 'GWDS',
                'sku' => 'GWDS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 445,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Goldwin brand dimmer switch for adjustable lighting levels.',
            ],
            [
                'name' => 'CR1GS1',
                'sku' => 'CR1GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 800,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Crystal brand 1 gang 1 way premium switch with elegant transparent design.',
            ],
            [
                'name' => 'CR1GS2',
                'sku' => 'CR1GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 980,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Crystal brand 1 gang 2 way premium switch with transparent finish for multi-location control.',
            ],
            [
                'name' => 'CR2GS1',
                'sku' => 'CR2GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 1140,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Crystal brand 2 gang 1 way premium switch with crystal-clear design for dual circuit control.',
            ],
            [
                'name' => 'FL1GS1',
                'sku' => 'FL1GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 188,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Flow brand 1 gang 1 way switch with sleek contemporary design for basic lighting control.',
            ],
            [
                'name' => 'FL1GS2',
                'sku' => 'FL1GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 305,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Flow brand 1 gang 2 way switch for multi-location lighting control.',
            ],
            [
                'name' => 'FL2GS1',
                'sku' => 'FL2GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 361,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Flow brand 2 gang 1 way switch for independent control of two circuits.',
            ],
            [
                'name' => 'FL2GS2',
                'sku' => 'FL2GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 440,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Flow brand 2 gang 2 way switch for dual circuit control from multiple locations.',
            ],
            [
                'name' => 'FL3GS1',
                'sku' => 'FL3GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 555,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Flow brand 3 gang 1 way switch for controlling three separate lighting circuits.',
            ],
            [
                'name' => 'CN1GS1',
                'sku' => 'CN1GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 210,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 1 gang 1 way switch with robust industrial design for basic lighting control.',
            ],
            [
                'name' => 'CN1GS2',
                'sku' => 'CN1GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 325,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 1 gang 2 way switch for multi-location lighting control.',
            ],
            [
                'name' => 'CN2GS1',
                'sku' => 'CN2GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 385,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 2 gang 1 way switch for independent control of two circuits.',
            ],
            [
                'name' => 'CN2GS2',
                'sku' => 'CN2GS2',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 475,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 2 gang 2 way switch for dual circuit control from multiple locations.',
            ],
            [
                'name' => 'CN3GS1',
                'sku' => 'CN3GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 490,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 3 gang 1 way switch for controlling three separate lighting circuits.',
            ],
            [
                'name' => 'CN4GS1',
                'sku' => 'CN4GS1',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 585,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 4 gang 1 way switch for centralized control of four lighting circuits.',
            ],
            [
                'name' => 'CN2PS',
                'sku' => 'CN2PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 485,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 2 gang power switch for appliance control.',
            ],
            [
                'name' => 'CN3PS13A',
                'sku' => 'CN3PS13A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 575,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 3 gang 13A power switch for heavy-duty appliances.',
            ],
            [
                'name' => 'CN5PS',
                'sku' => 'CN5PS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 735,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 5 gang power switch for multi-appliance control.',
            ],
            [
                'name' => 'CNDBS',
                'sku' => 'CNDBS',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 500,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand double pole switch for complete circuit isolation.',
            ],
            [
                'name' => 'CN3PRS15A',
                'sku' => 'CN3PRS15A',
                'category_id' => 1,
                'supplier_id' => 1,
                'price' => 675,
                'purchase_price' => 0,
                'stock_alert' => 10,
                'description' => 'Cannon brand 3 gang 15A push button switch for momentary heavy-load control.',
            ],



        ];

        foreach ($products as $product) {

            Product::updateOrCreate(
                ['sku' => $product['sku']],
                $product
            );
        }
    }
}
