<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\Category;
use App\Models\Product;
use App\Models\ProductImage;
use App\Models\Supplier;
use App\Services\BarcodeService;
use App\Traits\UploadHelper;
use Illuminate\Http\Request;
use Illuminate\Validation\Rule;
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
use PhpOffice\PhpSpreadsheet\Style\Alignment;
use PhpOffice\PhpSpreadsheet\Style\Border;
use PhpOffice\PhpSpreadsheet\Style\Color;
use PhpOffice\PhpSpreadsheet\Style\Fill;
use PhpOffice\PhpSpreadsheet\Style\Font;
use PhpOffice\PhpSpreadsheet\Cell\DataType;

class ProductController extends Controller
{
    use UploadHelper;

    /**
     * Display a listing of the resource.
     */
    public function index(Request $request)
    {
        $totalProducts = Product::count();
        $totalFeatured = Product::where('is_featured', true)->count();
        $suppliers     = Supplier::orderBy('company_name', 'asc')->get();
        return view('pages.admin.product.index', compact('totalProducts', 'totalFeatured', 'suppliers'));
    }

    public function fetchProductsIndexData(Request $request)
    {
        $query = Product::with(['supplier', 'category'])->orderBy('name', 'asc');

        if ($request->filled('search')) {
            $search = trim($request->search);
            $query->where(function ($q) use ($search) {
                $q->where('name', 'LIKE', "%{$search}%")
                  ->orWhere('sku', 'LIKE', "%{$search}%")
                  ->orWhere('barcode', 'LIKE', "%{$search}%");
            });
        }

        if ($request->filled('supplier_id')) {
            $query->where('supplier_id', $request->supplier_id);
        }

        if ($request->filled('featured')) {
            if ($request->featured === '1') {
                $query->where('is_featured', 1);
            } elseif ($request->featured === '0') {
                $query->where('is_featured', 0);
            }
        }

        $products = $query->paginate(25)->withQueryString();

        return response()->json([
            'table'          => view('pages.admin.product.table', compact('products'))->render(),
            'mobile'         => view('pages.admin.product.mtable', compact('products'))->render(),
            'pagination'     => (string) $products->links(),
            'total'          => $products->total(),
            'total_featured' => Product::where('is_featured', true)->count(),
        ]);
    }

    /**
     * Toggle the featured status of a product.
     */
    public function toggleFeatured(Product $product)
    {
        $product->is_featured = !$product->is_featured;
        $product->save();

        if (request()->ajax() || request()->wantsJson()) {
            return response()->json([
                'success'        => true,
                'is_featured'    => (bool) $product->is_featured,
                'total_featured' => Product::where('is_featured', true)->count(),
                'message'        => $product->is_featured ? 'Product marked as featured!' : 'Product unfeatured successfully!',
            ]);
        }

        return back()->with('success', $product->is_featured ? 'Product marked as featured!' : 'Product unfeatured successfully!');
    }

    /**
     * Export all products to a beautifully styled Excel file.
     */
    public function exportExcel()
    {
        $products = Product::with(['category', 'supplier'])
            ->orderBy('name', 'asc')
            ->get();

        $spreadsheet = new Spreadsheet();
        $sheet = $spreadsheet->getActiveSheet();
        $sheet->setTitle('Products');

        // ── Document Properties ──────────────────────────────────────────
        $spreadsheet->getProperties()
            ->setCreator('R.Electric')
            ->setLastModifiedBy('R.Electric')
            ->setTitle('Product List')
            ->setSubject('All Products Export')
            ->setDescription('Generated by DMS on ' . now()->format('d M Y'));

        // ── Column Widths (A-N = 14 columns, B = Image) ────────────────
        $colWidths = [
            'A' => 5,   // #
            'B' => 11,  // Image
            'C' => 28,  // Product Name
            'D' => 16,  // SKU
            'E' => 18,  // Barcode
            'F' => 14,  // Category
            'G' => 14,  // Supplier
            'H' => 12,  // Price
            'I' => 10,  // Weight (kg)
            'J' => 10,  // Length (cm)
            'K' => 10,  // Width (cm)
            'L' => 10,  // Height (cm)
            'M' => 10,  // Featured
            'N' => 11,  // Status
        ];
        foreach ($colWidths as $col => $width) {
            $sheet->getColumnDimension($col)->setWidth($width);
        }

        // Force SKU (D) and Barcode (E) columns to text — prevents scientific notation.
        $sheet->getStyle('D:D')->getNumberFormat()->setFormatCode('@');
        $sheet->getStyle('E:E')->getNumberFormat()->setFormatCode('@');

        // ── Title Row ────────────────────────────────────────────────────
        $sheet->mergeCells('A1:N1');
        $sheet->setCellValue('A1', 'R.Electric Product List');
        $sheet->getStyle('A1')->applyFromArray([
            'font'      => ['bold' => true, 'size' => 14, 'color' => ['argb' => 'FFFFFFFF']],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF1E40AF']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getRowDimension(1)->setRowHeight(36);

        // ── Sub-title Row ────────────────────────────────────────────────
        $sheet->mergeCells('A2:N2');
        $sheet->setCellValue('A2', 'Generated on: ' . now()->format('d M Y, h:i A') . '   |   Total Products: ' . $products->count() . '   |   Featured: ' . $products->where('is_featured', true)->count());
        $sheet->getStyle('A2')->applyFromArray([
            'font'      => ['italic' => true, 'size' => 10, 'color' => ['argb' => 'FF374151']],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FFE0E7FF']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
        ]);
        $sheet->getRowDimension(2)->setRowHeight(22);

        // ── Header Row ───────────────────────────────────────────────────
        $headers    = ['#', 'Image', 'Product Name', 'SKU', 'Barcode', 'Category', 'Supplier', 'Price (৳)', 'Weight (kg)', 'Length (cm)', 'Width (cm)', 'Height (cm)', 'Featured', 'Status'];
        $headerCols = ['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N'];
        foreach ($headers as $i => $header) {
            $sheet->setCellValue($headerCols[$i] . '3', $header);
        }
        $sheet->getStyle('A3:N3')->applyFromArray([
            'font'      => ['bold' => true, 'size' => 11, 'color' => ['argb' => 'FFFFFFFF']],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF3B82F6']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FFBFDBFE']]],
        ]);
        $sheet->getRowDimension(3)->setRowHeight(24);

        // Freeze header rows
        $sheet->freezePane('A4');

        // ── Data Rows ────────────────────────────────────────────────────
        $imgSize = 55; // px — thumbnail size in Excel
        $row = 4;
        foreach ($products as $idx => $product) {
            $isOdd    = ($idx % 2 === 0);
            $rowColor = $isOdd ? 'FFFFFFFF' : 'FFF0F9FF';

            // Row height must accommodate the image
            $sheet->getRowDimension($row)->setRowHeight(50);

            // -- Text cells --
            $sheet->setCellValue('A' . $row, $idx + 1);
            // B is the image column — leave empty, drawing will fill it
            $sheet->setCellValue('C' . $row, $product->name);
            $sheet->setCellValueExplicit('D' . $row, $product->sku,           DataType::TYPE_STRING);
            $sheet->setCellValueExplicit('E' . $row, $product->barcode ?? '—', DataType::TYPE_STRING);
            $sheet->setCellValue('F' . $row, $product->category->name ?? '—');
            $sheet->setCellValue('G' . $row, $product->supplier->company_name ?? '—');
            $sheet->setCellValue('H' . $row, number_format($product->price, 2));
            $sheet->setCellValue('I' . $row, $product->weight  !== null ? $product->weight  : '—');
            $sheet->setCellValue('J' . $row, $product->length  !== null ? $product->length  : '—');
            $sheet->setCellValue('K' . $row, $product->width   !== null ? $product->width   : '—');
            $sheet->setCellValue('L' . $row, $product->height  !== null ? $product->height  : '—');
            $sheet->setCellValue('M' . $row, $product->is_featured ? '⭐ Yes' : 'No');
            $sheet->setCellValue('N' . $row, $product->status ? 'Active' : 'Inactive');

            // -- Row styling --
            $sheet->getStyle('A' . $row . ':N' . $row)->applyFromArray([
                'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => $rowColor]],
                'alignment' => ['vertical' => Alignment::VERTICAL_CENTER, 'wrapText' => false],
                'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FFE2E8F0']]],
            ]);
            $sheet->getStyle('A' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle('B' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle('H' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_RIGHT);
            $sheet->getStyle('I' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle('J' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle('K' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle('L' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle('M' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);
            $sheet->getStyle('N' . $row)->getAlignment()->setHorizontal(Alignment::HORIZONTAL_CENTER);

            // Color-code Status cell (N)
            if ($product->status) {
                $sheet->getStyle('N' . $row)->getFont()->setColor(new Color('FF16A34A'));
                $sheet->getStyle('N' . $row)->getFont()->setBold(true);
            } else {
                $sheet->getStyle('N' . $row)->getFont()->setColor(new Color('FFDC2626'));
            }

            // Color-code Featured cell (M)
            if ($product->is_featured) {
                $sheet->getStyle('M' . $row)->getFont()->setColor(new Color('FFD97706'));
                $sheet->getStyle('M' . $row)->getFont()->setBold(true);
            }

            // -- Embed product image --
            $imgRelPath = $product->image ?? null;
            if ($imgRelPath) {
                $imgFullPath = public_path($imgRelPath);
                if (is_file($imgFullPath)) {
                    $drawing = new \PhpOffice\PhpSpreadsheet\Worksheet\Drawing();
                    $drawing->setName($product->name);
                    $drawing->setDescription($product->name);
                    $drawing->setPath($imgFullPath);
                    $drawing->setWidth($imgSize);
                    $drawing->setHeight($imgSize);
                    $drawing->setResizeProportional(true);
                    $drawing->setCoordinates('B' . $row);
                    // Small offset to center the image nicely inside the cell
                    $drawing->setOffsetX(5);
                    $drawing->setOffsetY(3);
                    $drawing->setWorksheet($sheet);
                }
            } else {
                $sheet->setCellValue('B' . $row, '—');
            }

            $row++;
        }

        // ── Summary Footer ───────────────────────────────────────────────
        $footerRow = $row;
        $sheet->mergeCells('A' . $footerRow . ':G' . $footerRow);
        $sheet->setCellValue('A' . $footerRow, 'TOTAL PRODUCTS: ' . $products->count());
        $sheet->setCellValue('H' . $footerRow, '৳ ' . number_format($products->sum('price'), 2));
        $sheet->getStyle('A' . $footerRow . ':N' . $footerRow)->applyFromArray([
            'font'      => ['bold' => true, 'size' => 11, 'color' => ['argb' => 'FFFFFFFF']],
            'fill'      => ['fillType' => Fill::FILL_SOLID, 'startColor' => ['argb' => 'FF1E40AF']],
            'alignment' => ['horizontal' => Alignment::HORIZONTAL_CENTER, 'vertical' => Alignment::VERTICAL_CENTER],
            'borders'   => ['allBorders' => ['borderStyle' => Border::BORDER_THIN, 'color' => ['argb' => 'FF3B82F6']]],
        ]);
        $sheet->getRowDimension($footerRow)->setRowHeight(26);

        // ── Outer Border ─────────────────────────────────────────────────
        $sheet->getStyle('A1:N' . $footerRow)->applyFromArray([
            'borders' => [
                'outline' => ['borderStyle' => Border::BORDER_MEDIUM, 'color' => ['argb' => 'FF1E40AF']],
            ],
        ]);

        // ── Stream Response ──────────────────────────────────────────────
        $filename = 'Products_' . now()->format('Y-m-d_His') . '.xlsx';

        return response()->streamDownload(function () use ($spreadsheet) {
            $writer = new Xlsx($spreadsheet);
            $writer->save('php://output');
        }, $filename, [
            'Content-Type'        => 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
            'Cache-Control'       => 'max-age=0',
            'Content-Disposition' => 'attachment; filename="' . $filename . '"',
        ]);
    }


    /**
     * Show the form for creating a new resource.
     */
    public function create()
    {
        $categories = Category::orderBy('name', 'asc')->get();
        $suppliers  = Supplier::orderBy('name', 'asc')->get();
        return view('pages.admin.product.create', compact('categories', 'suppliers'));
    }

    /**
     * Store a newly created resource in storage.
     */
    public function store(Request $request, BarcodeService $barcodeService)
    {
        $validated = $request->validate([
            'name'              => 'required|string|max:100',
            'sku'               => 'required|string|max:200|unique:products,sku',
            'barcode'           => 'nullable|string|max:100|unique:products,barcode',
            'category_id'       => 'nullable|exists:categories,id',
            'supplier_id'       => 'required|exists:suppliers,id',
            'price'             => 'required|numeric|min:0',
            'stock_alert'       => 'required|integer|min:0',
            'weight'            => 'nullable|numeric|min:0',
            'length'            => 'nullable|numeric|min:0',
            'height'            => 'nullable|numeric|min:0',
            'width'             => 'nullable|numeric|min:0',
            'short_description' => 'nullable|string|max:500',
            'long_description'  => 'nullable|string',
            'is_featured'       => 'nullable|boolean',
            'image'             => 'nullable|image|max:2048',
            'gallery.*'         => 'nullable|image|max:2048',
        ]);

        $barcode = $barcodeService->sanitize($request->barcode);
        $validated['barcode']     = $barcode ?: $barcodeService->generateUniqueBarcode();
        $validated['is_featured'] = $request->boolean('is_featured');
        $validated['purchase_price'] = 0; // Set to 0 by default; updated later via edit

        // Main thumbnail
        if ($request->hasFile('image')) {
            $validated['image'] = $this->uploadFile($request->file('image'), 'products');
        }

        $product = Product::create($validated);

        // Gallery images
        if ($request->hasFile('gallery')) {
            foreach ($request->file('gallery') as $index => $file) {
                $path = $this->uploadFile($file, 'products/gallery');
                ProductImage::create([
                    'product_id' => $product->id,
                    'image'      => $path,
                    'sort_order' => $index,
                    'is_active'  => true,
                ]);
            }
        }

        return redirect()->route('admin.products.show', $product)->with('success', 'Product added successfully!');
    }

    /**
     * Display the specified resource.
     */
    public function show(Product $product)
    {
        $product->load(['images', 'category', 'supplier']);
        return view('pages.admin.product.show', compact('product'));
    }

    /**
     * Show the form for editing the specified resource.
     */
    public function edit(Product $product)
    {
        $categories = Category::orderBy('name', 'asc')->get();
        $suppliers  = Supplier::orderBy('name', 'asc')->get();
        $product->load('images');
        return view('pages.admin.product.edit', compact('product', 'categories', 'suppliers'));
    }

    /**
     * Update the specified resource in storage.
     */
    public function update(Request $request, Product $product, BarcodeService $barcodeService)
    {
        $validated = $request->validate([
            'name'              => 'required|string|max:100',
            'sku'               => ['required', 'string', 'max:200', Rule::unique('products')->ignore($product->id)],
            'barcode'           => ['nullable', 'string', 'max:100', Rule::unique('products')->ignore($product->id)],
            'category_id'       => 'nullable|exists:categories,id',
            'supplier_id'       => 'required|exists:suppliers,id',
            'price'             => 'required|numeric|min:0',
            'purchase_price'    => 'nullable|numeric|min:0',
            'stock_alert'       => 'required|integer|min:0',
            'weight'            => 'nullable|numeric|min:0',
            'length'            => 'nullable|numeric|min:0',
            'height'            => 'nullable|numeric|min:0',
            'width'             => 'nullable|numeric|min:0',
            'short_description' => 'nullable|string|max:500',
            'long_description'  => 'nullable|string',
            'status'            => 'required|in:0,1',
            'is_featured'       => 'nullable|boolean',
            'image'             => 'nullable|image|max:2048',
            'gallery.*'         => 'nullable|image|max:2048',
        ]);

        $barcode = $barcodeService->sanitize($request->barcode);
        if ($barcode) {
            $validated['barcode'] = $barcode;
        } elseif (!$product->barcode) {
            $validated['barcode'] = $barcodeService->generateUniqueBarcode(null, $product->id);
        }

        $validated['is_featured']    = $request->boolean('is_featured');
        $validated['purchase_price'] = 0;

        // Replace main thumbnail
        if ($request->hasFile('image')) {
            $this->deleteFile($product->image);
            $validated['image'] = $this->uploadFile($request->file('image'), 'products');
        }

        $product->update($validated);

        // Delete selected gallery images
        if ($request->filled('delete_gallery')) {
            foreach ($request->delete_gallery as $imgId) {
                $img = ProductImage::where('id', $imgId)->where('product_id', $product->id)->first();
                if ($img) {
                    $this->deleteFile($img->image);
                    $img->delete();
                }
            }
        }

        // Add new gallery images
        if ($request->hasFile('gallery')) {
            $nextOrder = $product->images()->max('sort_order') + 1;
            foreach ($request->file('gallery') as $index => $file) {
                $path = $this->uploadFile($file, 'products/gallery');
                ProductImage::create([
                    'product_id' => $product->id,
                    'image'      => $path,
                    'sort_order' => $nextOrder + $index,
                    'is_active'  => true,
                ]);
            }
        }

        return redirect()->route('admin.products.show', $product)->with('success', 'Product updated successfully!');
    }

    /**
     * Remove the specified resource from storage.
     */
    public function destroy(Product $product)
    {
        if ($product->orderItems()->exists()) {
            return redirect()
                ->route('admin.products.index')
                ->with('error', 'This product cannot be deleted because it is associated with existing orders.');
        }

        if ($product->stockItems()->exists()) {
            return redirect()
                ->route('admin.products.index')
                ->with('error', 'This product cannot be deleted because stock-in records exist for this product.');
        }

        // Delete gallery images
        foreach ($product->images as $img) {
            $this->deleteFile($img->image);
            $img->delete();
        }

        $image = $product->image;
        $product->delete();
        $this->deleteFile($image);

        return redirect()
            ->route('admin.products.index')
            ->with('success', 'Product deleted successfully!');
    }
}
